Analyze flat file skim created from "b03" trajectory file
the script used is 'C:\Projects\Repo\Work\STM\tests\analyze_vehicle_trajectory.py'

This trajectory set is the HGAC 45 RE-RUN.

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
DYNUST_SKIM_DIR = r'C:\Projects\SWIFT\SWIFT_Workspace\Scenarios\Scenario_S0\STM\STM_A\01_DynusT\03_Model'
DYNUST_SKIM_FILE = os.path.join(DYNUST_SKIM_DIR, 'Vehicle_Skim.csv')
DYNUST_SKIM_FILE

'C:\\Projects\\SWIFT\\SWIFT_Workspace\\Scenarios\\Scenario_S0\\STM\\STM_A\\01_DynusT\\03_Model\\Vehicle_Skim.csv'

In [3]:
skim = pd.read_csv(DYNUST_SKIM_FILE)
skim.head()

,vid,tag,uclass,vtyp,origz,destz,nodes,node0,node1,start,end,delay,dist,totveh,purpose
0,48,2,3,2,412,412,1,92535,84113,0.0,0.024141,0.0,0.016094,0,2
1,18,2,3,1,176,176,1,15991,15992,0.0,0.004664,0.0,0.002721,4,5
2,60,2,3,1,104,104,1,286677,286896,0.0,0.050381,0.0,0.028542,8,1
3,31,2,3,6,313,313,1,74129,106229,0.0,0.091604,0.0,0.045802,12,5
4,72,2,3,2,182,182,2,107217,107221,0.0,0.136889,0.0,0.060922,16,2

In [4]:
skim.head(20)

,vid,tag,uclass,vtyp,origz,destz,nodes,node0,node1,start,end,delay,dist,totveh,purpose
0,48,2,3,2,412,412,1,92535,84113,0.0,0.024141,0.0,0.016094,0,2
1,18,2,3,1,176,176,1,15991,15992,0.0,0.004664,0.0,0.002721,4,5
2,60,2,3,1,104,104,1,286677,286896,0.0,0.050381,0.0,0.028542,8,1
3,31,2,3,6,313,313,1,74129,106229,0.0,0.091604,0.0,0.045802,12,5
4,72,2,3,2,182,182,2,107217,107221,0.0,0.136889,0.0,0.060922,16,2
5,141,2,3,1,4621,4623,1,449221,449306,0.1,0.176113,0.0,0.069771,24,2
6,177,2,3,3,59,59,1,11868,245719,0.1,0.110952,0.0,0.006853,28,4
7,165,2,3,1,4759,4759,1,452416,451672,0.1,0.132923,0.0,0.035666,32,2
8,132,2,3,2,316,316,1,106228,78874,0.1,0.101401,0.0,0.000707,36,2
9,63,2,3,2,183,183,1,305194,23563,0.0,0.104486,0.0,0.060950,40,4
10,198,2,3,1,103,103,1,268106,121341,0.1,0.112273,0.0,0.007159,44,4
11,316,2,3,2,65,65,1,284318,286502,0.2,0.244446,0.0,0.029630,48,4
12,15,2,3,6,153,153,3,309155,70523,0.0,0.297029,0.0,0.181211,52,5
13,310,2,3,5,123,123,1,302812,305552,0.2,0.221300,0.0,0.012425,64,5
14,309,2,3,1,313,313,1,106229,74129,0.2,0.266665,0.0,0.033333,68,3
15,117,2,3,2,275,275,2,18866,73655,0.1,0.214553,0.0,0.071762,72,4
16,312,2,3,3,42,42,1,275711,267654,0.2,0.260709,0.0,0.035414,80,4
17,303,2,3,5,36,36,1,18864,286109,0.2,0.237030,0.0,0.024665,84,5
18,425,2,3,1,303,303,1,271175,245471,0.3,0.379972,0.0,0.048591,88,1
19,32,2,3,1,240,240,4,278953,14054,0.0,0.330724,0.0,0.197844,92,1

In [5]:
total_vmt, total_vhd, total_vht = \
np.sum(skim.dist.values), np.sum(skim.delay.values) / 60.0, np.sum(skim.end.values - skim.start.values) / 60.0

In [6]:
print('Total VMT = {:,.0f}'.format(total_vmt))
print('Total VHT = {:,.0f}'.format(total_vht))
print('Total VHD = {:,.0f}'.format(total_vhd))

Total VMT = 325,366,516
Total VHT = 13,248,226
Total VHD = 2,000,222

In [12]:
skim.iloc[np.argmax(skim.dist.values)]

vid        1.099718e+07
tag        2.000000e+00
uclass     3.000000e+00
vtyp       1.000000e+00
origz      5.026000e+03
destz      4.864000e+03
nodes      1.860000e+02
node0      4.590660e+05
node1      4.707660e+05
start      7.250000e+02
end        9.446329e+02
delay      9.300000e+00
dist       1.948920e+02
totveh     1.791093e+09
purpose    3.000000e+00
Name: 17513911, dtype: float64

In [10]:
skim.loc[17513911:17513912, skim.columns]

,vid,tag,uclass,vtyp,origz,destz,nodes,node0,node1,start,end,delay,dist,totveh,purpose
17513911,10997184,2,3,1,5026,4864,186,459066,470766,725.0,944.632874,9.300,194.891953,1791093120,3
17513912,17018337,2,3,1,778,3452,35,297435,98881,911.0,944.692200,3.636,11.876823,1791093864,1